#!/bin/bash

# Direktori sementara yang aman untuk menyimpan config bersih
# /run adalah tmpfs, jadi file akan hilang saat reboot (ini bagus)
mkdir -p /run/xray

# Membersihkan config.json dari baris komentar dan menyimpannya ke file baru
# grep -v akan membuang semua baris yang mengandung pola '#'.
grep -v '#' /etc/xray/config.json > /run/xray/config.json

# Menjalankan xray dengan file konfigurasi yang sudah bersih
/usr/local/bin/xray run -config /run/xray/config.json
